baseURL: https://thallysrc.github.io/
languageCode: en-us
title: Thallys Rodrigues Costa
theme: "PaperMod"
googleAnalytics: G-888NRJSBTZ
languages:
  pt:
    languageName: "Português"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
params:
  env: production
    # menu:
    #   main:
    #     - name: Archive
    #       url: archives
    #       weight: 5
    #     - name: Search
    #       url: search/
    #       weight: 10

#  pt:
#    languageName: ":pt:"
#    languageAltTitle: Portugues
#    weight: 2
#    title: PaperModL2
#    taxonomies:
#      category: FRcategories
#      tag: FRtags
#      series: FRseries
#    profileMode:
#      enabled: true
#      title: PaperMod
#      imageUrl: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f317.svg"
#      imageTitle: ProfileMode image
#      # imageWidth: 120
#      # imageHeight: 120
#      subtitle: "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"
#      buttons:
#        - name: Blog
#          url: posts
#        - name: Profile Mode
#          url: https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode
#    menu:
#      main:
#        - name: Archive
#          url: archives/
#          weight: 5
#        - name: FRTags
#          url: frtags
#          weight: 10
#        - name: FRCategories
#          url: frcategories
#          weight: 10
#        - name: FRSeries
#          url: frseries
#          weight: 10
#        - name: NullLink
#          url: "#"
#  de:
#    languageName: ":de:"
#    languageAltTitle: French
#    weight: 2
#    title: PaperModL2
#    taxonomies:
#      category: FRcategories
#      tag: FRtags
#      series: FRseries
#    profileMode:
#      enabled: true
#      title: PaperMod
#      imageUrl: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f317.svg"
#      imageTitle: ProfileMode image
#      # imageWidth: 120
#      # imageHeight: 120
#      subtitle: "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"
#      buttons:
#        - name: Blog
#          url: posts
#        - name: Profile Mode
#          url: https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode
#    menu:
#      main:
#        - name: Archive
#          url: archives/
#          weight: 5
#        - name: FRTags
#          url: frtags
#          weight: 10
#        - name: FRCategories
#          url: frcategories
#          weight: 10
#        - name: FRSeries
#          url: frseries
#          weight: 10
#        - name: NullLink
#          url: "#"
